# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 996109e6166e371cfe77e8290725a429d90865f3a7c58e906b836540824e94f94e3e6367f18636a01fdc9a25d9e7f7bba33f78490fd8e3441b78d3170c392d21

test:
  secret_key_base: a17f23f446fa79ef78c9152d704c99c78211b483a7594e200930018a9a14893fd1dcf20d98102e9e05529ffe7a881d27259f326f58e6327c12b7958671db78c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
